# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b948edd030b73a75fa7f46784ba23d6169ecdfbc08f561697bb29ff692fb183473465dbe1eeacb3dda9d2d51b18c4c354e3cb29bfb9acaeccc5f66a5f3f92142

test:
  secret_key_base: b47e8c23a6850782fcf1f58dfafb116513934aa59c8352e16a0e8e4e4767d3f3b7d38f5451c715640c43428c1213e358a05bc54df186151e7f13faf246e08d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
